package com.monitor.parser.perfmon;

/* Generated By:JavaCC: Do not edit this line. PerfMonConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PerfMonConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 1;
  /** RegularExpression Id. */
  int BOM = 2;
  /** RegularExpression Id. */
  int SEPARATOR = 3;
  /** RegularExpression Id. */
  int VALUE = 4;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<EOL>",
    "\"\\ufeff\"",
    "\"\\t\"",
    "<VALUE>",
  };

}
